-- ProjectHub: первичная схема (Flyway baseline).
-- Совместимо с PostgreSQL и с H2 в режиме PostgreSQL.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login         VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(200) NOT NULL,
    role          VARCHAR(16)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_login UNIQUE (login)
);

CREATE INDEX idx_users_login ON users (login);

CREATE TABLE projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(16)  NOT NULL,
    owner_id    BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_projects_owner ON projects (owner_id);
CREATE INDEX idx_projects_status ON projects (status);

CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(4000),
    status      VARCHAR(16)  NOT NULL,
    deadline    DATE,
    project_id  BIGINT       NOT NULL,
    assignee_id BIGINT,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_tasks_project  FOREIGN KEY (project_id)  REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_tasks_assignee FOREIGN KEY (assignee_id) REFERENCES users (id)
);

CREATE INDEX idx_tasks_project  ON tasks (project_id);
CREATE INDEX idx_tasks_assignee ON tasks (assignee_id);
CREATE INDEX idx_tasks_status   ON tasks (status);
CREATE INDEX idx_tasks_deadline ON tasks (deadline);

CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(4000) NOT NULL,
    task_id    BIGINT        NOT NULL,
    author_id  BIGINT        NOT NULL,
    created_at TIMESTAMP     NOT NULL,
    CONSTRAINT fk_comments_task   FOREIGN KEY (task_id)   REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE INDEX idx_comments_task   ON comments (task_id);
CREATE INDEX idx_comments_author ON comments (author_id);
