-- ProjectHub: лок аккаунтов после серии неудачных входов + журнал аудита.

ALTER TABLE users ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN locked_until          TIMESTAMP;

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      VARCHAR(64)   NOT NULL,
    actor       VARCHAR(64),
    target_type VARCHAR(32),
    target_id   BIGINT,
    details     VARCHAR(1000),
    ip          VARCHAR(64),
    created_at  TIMESTAMP     NOT NULL
);

CREATE INDEX idx_audit_log_created_at ON audit_log (created_at);
CREATE INDEX idx_audit_log_action     ON audit_log (action);
CREATE INDEX idx_audit_log_actor      ON audit_log (actor);
