-- ProjectHub: трекер рабочего времени по задачам.

CREATE TABLE time_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    start_at    TIMESTAMP    NOT NULL,
    end_at      TIMESTAMP,
    duration_seconds BIGINT,
    note        VARCHAR(500),
    CONSTRAINT fk_time_entries_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_time_entries_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_time_entries_task    ON time_entries (task_id);
CREATE INDEX idx_time_entries_user    ON time_entries (user_id);
CREATE INDEX idx_time_entries_start   ON time_entries (start_at);
-- Уникальность одного активного таймера на пользователя обеспечивается на уровне сервиса
-- (partial index в H2 не поддерживается).
