-- ProjectHub V3: Hibernate Envers — журнал ревизий для @Audited сущностей.
-- Совместимо с PostgreSQL 16 и H2 в режиме PostgreSQL.
--
-- Сейчас аудитом покрыта только Task. Если в будущем добавятся @Audited на другие сущности,
-- их *_AUD таблицы создавайте отдельной миграцией V4__... — Envers сам не управляет схемой
-- при ddl-auto=validate.

-- Глобальная таблица ревизий: одна на всё приложение.
CREATE TABLE revinfo (
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- История изменений задач. Композитный PK (id, rev) даёт нам полный snapshot задачи на каждую правку.
-- REVTYPE: 0 — INSERT, 1 — UPDATE, 2 — DELETE.
-- Колонки повторяют tasks (включая audit-колонки из V2). NULL'able, потому что для DELETE
-- Envers пишет null'ы по умолчанию. Поле version не аудируем
-- (do_not_audit_optimistic_locking_field=true в Hibernate 6 по умолчанию).
CREATE TABLE tasks_aud (
    id          BIGINT       NOT NULL,
    rev         INTEGER      NOT NULL,
    revtype     SMALLINT,
    title       VARCHAR(200),
    description VARCHAR(4000),
    status      VARCHAR(16),
    deadline    DATE,
    project_id  BIGINT,
    assignee_id BIGINT,
    created_at  TIMESTAMP,
    created_by  VARCHAR(64),
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(64),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_tasks_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX idx_tasks_aud_rev ON tasks_aud (rev);
CREATE INDEX idx_tasks_aud_id  ON tasks_aud (id);
