-- ProjectHub: уведомления для пользователей.

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT      NOT NULL,
    type        VARCHAR(40)  NOT NULL,
    title       VARCHAR(200) NOT NULL,
    message     VARCHAR(500),
    link        VARCHAR(255),
    read_at     TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_recipient ON notifications (recipient_id);
CREATE INDEX idx_notifications_unread    ON notifications (recipient_id, read_at);
CREATE INDEX idx_notifications_created   ON notifications (created_at);
