-- v4-quick-wins:
--   • приоритет задач (enum LOW/MEDIUM/HIGH/URGENT) — поле + индекс для сортировки
--   • теги задач — отдельная связная таблица tasks_tags (плоская denormalized строка)
--   • вложения файлов к задачам — task_attachments с метаданными
--   • email-уведомлений: поле email + флаг согласия у пользователя
--
-- Все колонки nullable, чтобы не падать на сидере и существующих данных.

-- 1) Приоритет задач
ALTER TABLE tasks ADD COLUMN priority VARCHAR(16) NOT NULL DEFAULT 'MEDIUM';
CREATE INDEX idx_tasks_priority ON tasks (priority);

-- 2) Теги задач: many-to-many через side-таблицу.
--    Один тег — это просто строка; не отдельная сущность, чтобы упростить пикер.
CREATE TABLE task_tags (
    task_id  BIGINT       NOT NULL,
    tag      VARCHAR(40)  NOT NULL,
    CONSTRAINT pk_task_tags PRIMARY KEY (task_id, tag),
    CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);
CREATE INDEX idx_task_tags_tag ON task_tags (tag);

-- 3) Вложения файлов
CREATE TABLE task_attachments (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id       BIGINT       NOT NULL,
    filename      VARCHAR(255) NOT NULL,
    storage_path  VARCHAR(500) NOT NULL,
    content_type  VARCHAR(100),
    size_bytes    BIGINT,
    uploaded_by   VARCHAR(64),
    uploaded_at   TIMESTAMP    NOT NULL,
    CONSTRAINT fk_attach_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);
CREATE INDEX idx_task_attachments_task ON task_attachments (task_id);

-- 4) Email пользователя + согласие на рассылку
ALTER TABLE users ADD COLUMN email VARCHAR(160);
ALTER TABLE users ADD COLUMN email_notifications BOOLEAN NOT NULL DEFAULT TRUE;
